// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:yetuga/utils/logger.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB229Uz4jPPx0zO_awGYp8vDhxrryuBocU',
    appId: '1:627575427248:web:b584190500b11f53daeb75',
    messagingSenderId: '627575427248',
    projectId: 'yetuga-1d0d9',
    authDomain: 'yetuga-1d0d9.firebaseapp.com',
    storageBucket: 'yetuga-1d0d9.firebasestorage.app',
    measurementId: 'G-RYDS5RRPJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI7aQHjBrqTfugnc749008mdI6wHYgVrY',
    appId: '1:627575427248:android:ad5a994b8b6c9d2fdaeb75',
    messagingSenderId: '627575427248',
    projectId: 'yetuga-1d0d9',
    storageBucket: 'yetuga-1d0d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ13HAk0bNQga2nzoCEXCuscqOUYxWl28',
    appId: '1:627575427248:ios:a3b37965e5e83fbddaeb75',
    messagingSenderId: '627575427248',
    projectId: 'yetuga-1d0d9',
    storageBucket: 'yetuga-1d0d9.firebasestorage.app',
    iosBundleId: 'com.example.yetuga',
  );
}